USE Volei;

-- Tabela País
CALL AdicionarPais('Brasil', @novoPaisId);
CALL AdicionarPais('Portugal', @novoPaisId);
CALL AdicionarPais('Estados Unidos', @novoPaisId);
CALL AdicionarPais('Itália', @novoPaisId);
CALL AdicionarPais('França', @novoPaisId);
CALL AdicionarPais('Alemanha', @novoPaisId);
CALL AdicionarPais('Espanha', @novoPaisId);
CALL AdicionarPais('Argentina', @novoPaisId);
CALL AdicionarPais('China', @novoPaisId);
CALL AdicionarPais('Japão', @novoPaisId);
CALL AdicionarPais('Rússia', @novoPaisId);
CALL AdicionarPais('Austrália', @novoPaisId);
CALL AdicionarPais('Canadá', @novoPaisId);
CALL AdicionarPais('México', @novoPaisId);
CALL AdicionarPais('Suécia', @novoPaisId);
CALL AdicionarPais('Noruega', @novoPaisId);
CALL AdicionarPais('Dinamarca', @novoPaisId);
CALL AdicionarPais('Finlândia', @novoPaisId);
CALL AdicionarPais('Índia', @novoPaisId);
CALL AdicionarPais('África do Sul', @novoPaisId);

-- Tabela Estádio
CALL AdicionarEstadio('Madison Square Garden', 20789, 'Nova York, EUA', @novoEstadioId);
CALL AdicionarEstadio('Staples Center', 19060, 'Los Angeles, EUA', @novoEstadioId);
CALL AdicionarEstadio('O2 Arena', 20000, 'Londres, Reino Unido', @novoEstadioId);
CALL AdicionarEstadio('Barclays Center', 17732, 'Brooklyn, EUA', @novoEstadioId);
CALL AdicionarEstadio('Wembley Arena', 12500, 'Londres, Reino Unido', @novoEstadioId);
CALL AdicionarEstadio('SSE Hydro', 14000, 'Glasgow, Reino Unido', @novoEstadioId);
CALL AdicionarEstadio('AccorHotels Arena', 20000, 'Paris, França', @novoEstadioId);
CALL AdicionarEstadio('Mercedes-Benz Arena', 17000, 'Berlim, Alemanha', @novoEstadioId);
CALL AdicionarEstadio('Arena Ciudad de México', 22000, 'Cidade do México, México', @novoEstadioId);
CALL AdicionarEstadio('Scotiabank Arena', 19800, 'Toronto, Canadá', @novoEstadioId);
CALL AdicionarEstadio('Rod Laver Arena', 15000, 'Melbourne, Austrália', @novoEstadioId);
CALL AdicionarEstadio('Saitama Super Arena', 37000, 'Saitama, Japão', @novoEstadioId);
CALL AdicionarEstadio('Maracanã', 78000, 'Rio de Janeiro, Brasil', @novoEstadioId);
CALL AdicionarEstadio('Allianz Arena', 75000, 'Munique, Alemanha', @novoEstadioId);
CALL AdicionarEstadio('San Siro', 80018, 'Milão, Itália', @novoEstadioId);

-- Tabela Pessoa / Jogador
CALL AdicionarJogador('João Pedro', 'joao.pedro@example.com', '111111111', 'Rua C', 'Bairro 3', 'Cidade Z', 1.85, 75, 'Central', 'João', 'Pedro', 'Brasileira', 1, @novoJogadorId);
CALL AdicionarJogador('Ana Silva', 'ana.silva@example.com', '222222222', 'Rua D', 'Bairro 4', 'Cidade W', 1.75, 65, 'Ponta', 'Ana', 'Silva', 'Portuguesa', 2, @novoJogadorId);
CALL AdicionarJogador('Pedro Santos', 'pedro.santos@example.com', '333333333', 'Rua E', 'Bairro 5', 'Cidade X', 1.90, 85, 'Libero', 'Pedro', 'Santos', 'Brasileira', 1, @novoJogadorId);
CALL AdicionarJogador('Maria Costa', 'maria.costa@example.com', '444444444', 'Rua F', 'Bairro 6', 'Cidade Y', 1.70, 60, 'Central', 'Maria', 'Costa', 'Portuguesa', 2, @novoJogadorId);
CALL AdicionarJogador('Lucas Lima', 'lucas.lima@example.com', '555555555', 'Rua G', 'Bairro 7', 'Cidade V', 1.88, 80, 'Oposto', 'Lucas', 'Lima', 'Brasileira', 3, @novoJogadorId);
CALL AdicionarJogador('Gabriel Silva', 'gabriel.silva@example.com', '666666666', 'Rua H', 'Bairro 8', 'Cidade U', 1.92, 85, 'Central', 'Gabriel', 'Silva', 'Brasileira', 4, @novoJogadorId);
CALL AdicionarJogador('Rafael Nunes', 'rafael.nunes@example.com', '777777777', 'Rua I', 'Bairro 9', 'Cidade T', 1.85, 78, 'Ponta', 'Rafael', 'Nunes', 'Portuguesa', 5, @novoJogadorId);
CALL AdicionarJogador('Thiago Souza', 'thiago.souza@example.com', '888888888', 'Rua J', 'Bairro 10', 'Cidade S', 1.90, 82, 'Libero', 'Thiago', 'Souza', 'Brasileira', 6, @novoJogadorId);
CALL AdicionarJogador('Felipe Costa', 'felipe.costa@example.com', '999999999', 'Rua K', 'Bairro 11', 'Cidade R', 1.87, 79, 'Oposto', 'Felipe', 'Costa', 'Brasileira', 7, @novoJogadorId);
CALL AdicionarJogador('Rodrigo Alves', 'rodrigo.alves@example.com', '101010101', 'Rua L', 'Bairro 12', 'Cidade Q', 1.93, 88, 'Central', 'Rodrigo', 'Alves', 'Brasileira', 8, @novoJogadorId);
CALL AdicionarJogador('Bruno Fernandes', 'bruno.fernandes@example.com', '111111112', 'Rua M', 'Bairro 13', 'Cidade P', 1.86, 81, 'Ponta', 'Bruno', 'Fernandes', 'Portuguesa', 9, @novoJogadorId);
CALL AdicionarJogador('Carlos Oliveira', 'carlos.oliveira@example.com', '121212121', 'Rua N', 'Bairro 14', 'Cidade O', 1.89, 83, 'Libero', 'Carlos', 'Oliveira', 'Brasileira', 10, @novoJogadorId);
CALL AdicionarJogador('Paulo Mendes', 'paulo.mendes@example.com', '131313131', 'Rua O', 'Bairro 15', 'Cidade N', 1.91, 86, 'Oposto', 'Paulo', 'Mendes', 'Brasileira', 11, @novoJogadorId);
CALL AdicionarJogador('Eduardo Ribeiro', 'eduardo.ribeiro@example.com', '141414141', 'Rua P', 'Bairro 16', 'Cidade M', 1.84, 77, 'Central', 'Eduardo', 'Ribeiro', 'Brasileira', 12, @novoJogadorId);
CALL AdicionarJogador('Leonardo Azevedo', 'leonardo.azevedo@example.com', '151515151', 'Rua Q', 'Bairro 17', 'Cidade L', 1.90, 82, 'Ponta', 'Leonardo', 'Azevedo', 'Brasileira', 13, @novoJogadorId);
CALL AdicionarJogador('Ricardo Lima', 'ricardo.lima@example.com', '161616161', 'Rua R', 'Bairro 18', 'Cidade K', 1.92, 85, 'Libero', 'Ricardo', 'Lima', 'Portuguesa', 14, @novoJogadorId);
CALL AdicionarJogador('André Alves', 'andre.alves@example.com', '171717171', 'Rua S', 'Bairro 19', 'Cidade J', 1.88, 80, 'Oposto', 'André', 'Alves', 'Brasileira', 15, @novoJogadorId);
CALL AdicionarJogador('Marcos Silva', 'marcos.silva@example.com', '181818181', 'Rua T', 'Bairro 20', 'Cidade I', 1.85, 78, 'Central', 'Marcos', 'Silva', 'Brasileira', 16, @novoJogadorId);
CALL AdicionarJogador('Bruna Santos', 'bruna.santos@example.com', '191919191', 'Rua U', 'Bairro 21', 'Cidade H', 1.75, 65, 'Ponta', 'Bruna', 'Santos', 'Brasileira', 17, @novoJogadorId);
CALL AdicionarJogador('Camila Oliveira', 'camila.oliveira@example.com', '202020202', 'Rua V', 'Bairro 22', 'Cidade G', 1.78, 68, 'Libero', 'Camila', 'Oliveira', 'Brasileira', 18, @novoJogadorId);
CALL AdicionarJogador('Juliana Costa', 'juliana.costa@example.com', '212121212', 'Rua W', 'Bairro 23', 'Cidade F', 1.80, 70, 'Oposto', 'Juliana', 'Costa', 'Brasileira', 19, @novoJogadorId);
CALL AdicionarJogador('Patrícia Lima', 'patricia.lima@example.com', '222222222', 'Rua X', 'Bairro 24', 'Cidade E', 1.82, 72, 'Central', 'Patrícia', 'Lima', 'Brasileira', 20, @novoJogadorId);

-- Tabela Treinador
CALL AdicionarTreinador('Carlos Oliveira', 'carlos.oliveira@example.com', '555555555', 'Rua G', 'Bairro 7', 'Cidade Z', 'Carlos', 'Oliveira', 'Brasileira', 1, @novoTreinadorId);
CALL AdicionarTreinador('Beatriz Lima', 'beatriz.lima@example.com', '666666666', 'Rua H', 'Bairro 8', 'Cidade W', 'Beatriz', 'Lima', 'Portuguesa', 2, @novoTreinadorId);
CALL AdicionarTreinador('Rafael Nunes', 'rafael.nunes@example.com', '777777777', 'Rua I', 'Bairro 9', 'Cidade X', 'Rafael', 'Nunes', 'Brasileira', 1, @novoTreinadorId);
CALL AdicionarTreinador('Fernanda Azevedo', 'fernanda.azevedo@example.com', '888888888', 'Rua J', 'Bairro 10', 'Cidade Y', 'Fernanda', 'Azevedo', 'Portuguesa', 2, @novoTreinadorId);
CALL AdicionarTreinador('Lucas Almeida', 'lucas.almeida@example.com', '999999999', 'Rua K', 'Bairro 11', 'Cidade V', 'Lucas', 'Almeida', 'Brasileira', 3, @novoTreinadorId);
CALL AdicionarTreinador('Gabriela Costa', 'gabriela.costa@example.com', '101010101', 'Rua L', 'Bairro 12', 'Cidade U', 'Gabriela', 'Costa', 'Portuguesa', 4, @novoTreinadorId);
CALL AdicionarTreinador('Pedro Santos', 'pedro.santos@example.com', '111111112', 'Rua M', 'Bairro 13', 'Cidade T', 'Pedro', 'Santos', 'Brasileira', 5, @novoTreinadorId);
CALL AdicionarTreinador('Mariana Ferreira', 'mariana.ferreira@example.com', '121212121', 'Rua N', 'Bairro 14', 'Cidade S', 'Mariana', 'Ferreira', 'Brasileira', 6, @novoTreinadorId);
CALL AdicionarTreinador('Renato Lima', 'renato.lima@example.com', '131313131', 'Rua O', 'Bairro 15', 'Cidade R', 'Renato', 'Lima', 'Portuguesa', 7, @novoTreinadorId);
CALL AdicionarTreinador('Júlia Martins', 'julia.martins@example.com', '141414141', 'Rua P', 'Bairro 16', 'Cidade Q', 'Júlia', 'Martins', 'Brasileira', 8, @novoTreinadorId);
CALL AdicionarTreinador('Ricardo Alves', 'ricardo.alves@example.com', '151515151', 'Rua Q', 'Bairro 17', 'Cidade P', 'Ricardo', 'Alves', 'Brasileira', 9, @novoTreinadorId);
CALL AdicionarTreinador('Amanda Ribeiro', 'amanda.ribeiro@example.com', '161616161', 'Rua R', 'Bairro 18', 'Cidade O', 'Amanda', 'Ribeiro', 'Portuguesa', 10, @novoTreinadorId);
CALL AdicionarTreinador('Bruno Costa', 'bruno.costa@example.com', '171717171', 'Rua S', 'Bairro 19', 'Cidade N', 'Bruno', 'Costa', 'Brasileira', 11, @novoTreinadorId);
CALL AdicionarTreinador('Daniela Lima', 'daniela.lima@example.com', '181818181', 'Rua T', 'Bairro 20', 'Cidade M', 'Daniela', 'Lima', 'Portuguesa', 12, @novoTreinadorId);
CALL AdicionarTreinador('Fernando Sousa', 'fernando.sousa@example.com', '191919191', 'Rua U', 'Bairro 21', 'Cidade L', 'Fernando', 'Sousa', 'Brasileira', 13, @novoTreinadorId);
CALL AdicionarTreinador('Helena Alves', 'helena.alves@example.com', '202020202', 'Rua V', 'Bairro 22', 'Cidade K', 'Helena', 'Alves', 'Portuguesa', 14, @novoTreinadorId);
CALL AdicionarTreinador('Igor Mendes', 'igor.mendes@example.com', '212121212', 'Rua W', 'Bairro 23', 'Cidade J', 'Igor', 'Mendes', 'Brasileira', 15, @novoTreinadorId);
CALL AdicionarTreinador('Juliana Costa', 'juliana.costa@example.com', '222222222', 'Rua X', 'Bairro 24', 'Cidade I', 'Juliana', 'Costa', 'Brasileira', 16, @novoTreinadorId);
CALL AdicionarTreinador('Karen Silva', 'karen.silva@example.com', '232323232', 'Rua Y', 'Bairro 25', 'Cidade H', 'Karen', 'Silva', 'Portuguesa', 17, @novoTreinadorId);
CALL AdicionarTreinador('Leonardo Oliveira', 'leonardo.oliveira@example.com', '242424242', 'Rua Z', 'Bairro 26', 'Cidade G', 'Leonardo', 'Oliveira', 'Brasileira', 18, @novoTreinadorId);

-- Tabela Time
CALL AdicionarTime('Zenit Kazan', @novoTimeId);
CALL AdicionarTime('Lokomotiv Novosibirsk', @novoTimeId);
CALL AdicionarTime('Dinamo Moscow', @novoTimeId);
CALL AdicionarTime('Belogorie Belgorod', @novoTimeId);
CALL AdicionarTime('Cucine Lube Civitanova', @novoTimeId);
CALL AdicionarTime('Sir Safety Perugia', @novoTimeId);
CALL AdicionarTime('Modena Volley', @novoTimeId);
CALL AdicionarTime('Trentino Volley', @novoTimeId);
CALL AdicionarTime('Fenerbahçe', @novoTimeId);
CALL AdicionarTime('Halkbank Ankara', @novoTimeId);
CALL AdicionarTime('Ziraat Bankasi Ankara', @novoTimeId);
CALL AdicionarTime('PAOK Thessaloniki', @novoTimeId);
CALL AdicionarTime('Olympiacos', @novoTimeId);
CALL AdicionarTime('Panathinaikos', @novoTimeId);
CALL AdicionarTime('Berlin Recycling Volleys', @novoTimeId);
CALL AdicionarTime('VfB Friedrichshafen', @novoTimeId);
CALL AdicionarTime('Asseco Resovia', @novoTimeId);
CALL AdicionarTime('PGE Skra Bełchatów', @novoTimeId);
CALL AdicionarTime('Jastrzębski Węgiel', @novoTimeId);
CALL AdicionarTime('Trefl Gdańsk', @novoTimeId);

-- Tabela Partida
CALL AdicionarPartida(1, 30, 1, '2024-06-03', '01:40:00', @novaPartidaId);
CALL AdicionarPartida(2, 25, 2, '2024-06-10', '01:30:00', @novaPartidaId);
CALL AdicionarPartida(3, 28, 3, '2024-06-17', '01:45:00', @novaPartidaId);
CALL AdicionarPartida(4, 22, 4, '2024-06-24', '01:20:00', @novaPartidaId);
CALL AdicionarPartida(5, 26, 5, '2024-07-01', '01:50:00', @novaPartidaId);
CALL AdicionarPartida(6, 24, 6, '2024-07-08', '01:35:00', @novaPartidaId);
CALL AdicionarPartida(7, 29, 7, '2024-07-15', '01:55:00', @novaPartidaId);
CALL AdicionarPartida(8, 21, 8, '2024-07-22', '01:25:00', @novaPartidaId);
CALL AdicionarPartida(9, 27, 9, '2024-07-29', '01:45:00', @novaPartidaId);
CALL AdicionarPartida(10, 23, 10, '2024-08-05', '01:30:00', @novaPartidaId);
CALL AdicionarPartida(11, 28, 11, '2024-08-12', '01:40:00', @novaPartidaId);
CALL AdicionarPartida(12, 22, 12, '2024-08-19', '01:20:00', @novaPartidaId);
CALL AdicionarPartida(13, 26, 13, '2024-08-26', '01:50:00', @novaPartidaId);
CALL AdicionarPartida(14, 24, 14, '2024-09-02', '01:35:00', @novaPartidaId);
CALL AdicionarPartida(15, 29, 15, '2024-09-09', '01:55:00', @novaPartidaId);
CALL AdicionarPartida(16, 21, 16, '2024-09-16', '01:25:00', @novaPartidaId);
CALL AdicionarPartida(17, 27, 17, '2024-09-23', '01:45:00', @novaPartidaId);
CALL AdicionarPartida(18, 23, 18, '2024-09-30', '01:30:00', @novaPartidaId);
CALL AdicionarPartida(19, 28, 19, '2024-10-07', '01:40:00', @novaPartidaId);
CALL AdicionarPartida(20, 22, 20, '2024-10-14', '01:20:00', @novaPartidaId);

-- Tabela Patrocinador
CALL AdicionarPatrocinador('Nike', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Adidas', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Puma', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Under Armour', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Reebok', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Asics', @novoPatrocinadorId);
CALL AdicionarPatrocinador('New Balance', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Columbia', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Patagonia', @novoPatrocinadorId);
CALL AdicionarPatrocinador('The North Face', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Vans', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Converse', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Skechers', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Fila', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Champion', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Lululemon', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Ralph Lauren', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Lacoste', @novoPatrocinadorId);
CALL AdicionarPatrocinador('H&M', @novoPatrocinadorId);
CALL AdicionarPatrocinador('Zara', @novoPatrocinadorId);

-- Inscrever times em campeonatos
CALL AdicionarInscricaoTimeCampeonato(1, 1);
CALL AdicionarInscricaoTimeCampeonato(2, 1);
CALL AdicionarInscricaoTimeCampeonato(3, 1);
CALL AdicionarInscricaoTimeCampeonato(4, 1);
CALL AdicionarInscricaoTimeCampeonato(5, 1);
CALL AdicionarInscricaoTimeCampeonato(6, 1);
CALL AdicionarInscricaoTimeCampeonato(7, 1);
CALL AdicionarInscricaoTimeCampeonato(8, 1);
CALL AdicionarInscricaoTimeCampeonato(9, 1);
CALL AdicionarInscricaoTimeCampeonato(10, 1);
CALL AdicionarInscricaoTimeCampeonato(11, 1);
CALL AdicionarInscricaoTimeCampeonato(12, 1);
CALL AdicionarInscricaoTimeCampeonato(13, 1);
CALL AdicionarInscricaoTimeCampeonato(14, 1);
CALL AdicionarInscricaoTimeCampeonato(15, 1);
CALL AdicionarInscricaoTimeCampeonato(16, 1);
CALL AdicionarInscricaoTimeCampeonato(17, 1);
CALL AdicionarInscricaoTimeCampeonato(18, 1);
CALL AdicionarInscricaoTimeCampeonato(19, 1);
CALL AdicionarInscricaoTimeCampeonato(20, 1);

-- Registrar times em partidas
CALL AdicionarRegistroPartidaTime(1, 1);
CALL AdicionarRegistroPartidaTime(2, 2);
CALL AdicionarRegistroPartidaTime(3, 3);
CALL AdicionarRegistroPartidaTime(4, 4);
CALL AdicionarRegistroPartidaTime(5, 5);
CALL AdicionarRegistroPartidaTime(6, 6);
CALL AdicionarRegistroPartidaTime(7, 7);
CALL AdicionarRegistroPartidaTime(8, 8);
CALL AdicionarRegistroPartidaTime(9, 9);
CALL AdicionarRegistroPartidaTime(10, 10);
CALL AdicionarRegistroPartidaTime(11, 11);
CALL AdicionarRegistroPartidaTime(12, 12);
CALL AdicionarRegistroPartidaTime(13, 13);
CALL AdicionarRegistroPartidaTime(14, 14);
CALL AdicionarRegistroPartidaTime(15, 15);
CALL AdicionarRegistroPartidaTime(16, 16);
CALL AdicionarRegistroPartidaTime(17, 17);
CALL AdicionarRegistroPartidaTime(18, 18);
CALL AdicionarRegistroPartidaTime(19, 19);
CALL AdicionarRegistroPartidaTime(20, 20);

-- Tabela Pessoa
CALL AtualizarDadosPessoa(1, 'João Silva', 'joao.silva@example.com', '123456789', 'Rua A', 'Bairro 1', 'Cidade X');
CALL AtualizarDadosPessoa(2, 'Maria Oliveira', 'maria.oliveira@example.com', '987654321', 'Rua B', 'Bairro 2', 'Cidade Y');
CALL AtualizarDadosPessoa(3, 'Ana Costa', 'ana.costa@example.com', '555555555', 'Rua C', 'Bairro 3', 'Cidade Z');
CALL AtualizarDadosPessoa(4, 'Carlos Santos', 'carlos.santos@example.com', '666666666', 'Rua D', 'Bairro 4', 'Cidade W');
CALL AtualizarDadosPessoa(5, 'Lucas Lima', 'lucas.lima@example.com', '777777777', 'Rua E', 'Bairro 5', 'Cidade V');
CALL AtualizarDadosPessoa(6, 'Mariana Rocha', 'mariana.rocha@example.com', '888888888', 'Rua F', 'Bairro 6', 'Cidade U');
CALL AtualizarDadosPessoa(7, 'Gabriel Santos', 'gabriel.santos@example.com', '999999999', 'Rua G', 'Bairro 7', 'Cidade T');
CALL AtualizarDadosPessoa(8, 'Lara Costa', 'lara.costa@example.com', '101010101', 'Rua H', 'Bairro 8', 'Cidade S');
CALL AtualizarDadosPessoa(9, 'Rodrigo Almeida', 'rodrigo.almeida@example.com', '202020202', 'Rua I', 'Bairro 9', 'Cidade R');
CALL AtualizarDadosPessoa(10, 'Fernanda Lima', 'fernanda.lima@example.com', '303030303', 'Rua J', 'Bairro 10', 'Cidade Q');
CALL AtualizarDadosPessoa(11, 'Rafael Oliveira', 'rafael.oliveira@example.com', '404040404', 'Rua K', 'Bairro 11', 'Cidade P');
CALL AtualizarDadosPessoa(12, 'Camila Souza', 'camila.souza@example.com', '505050505', 'Rua L', 'Bairro 12', 'Cidade O');
CALL AtualizarDadosPessoa(13, 'Marcelo Ferreira', 'marcelo.ferreira@example.com', '606060606', 'Rua M', 'Bairro 13', 'Cidade N');
CALL AtualizarDadosPessoa(14, 'Patrícia Moreira', 'patricia.moreira@example.com', '707070707', 'Rua N', 'Bairro 14', 'Cidade M');
CALL AtualizarDadosPessoa(15, 'Bruno Lima', 'bruno.lima@example.com', '808080808', 'Rua O', 'Bairro 15', 'Cidade L');
CALL AtualizarDadosPessoa(16, 'Carolina Ribeiro', 'carolina.ribeiro@example.com', '909090909', 'Rua P', 'Bairro 16', 'Cidade K');
CALL AtualizarDadosPessoa(17, 'Thiago Gomes', 'thiago.gomes@example.com', '010101010', 'Rua Q', 'Bairro 17', 'Cidade J');
CALL AtualizarDadosPessoa(18, 'Vanessa Fernandes', 'vanessa.fernandes@example.com', '121212121', 'Rua R', 'Bairro 18', 'Cidade I');
CALL AtualizarDadosPessoa(19, 'Matheus Barbosa', 'matheus.barbosa@example.com', '131313131', 'Rua S', 'Bairro 19', 'Cidade H');
CALL AtualizarDadosPessoa(20, 'Aline Carvalho', 'aline.carvalho@example.com', '141414141', 'Rua T', 'Bairro 20', 'Cidade G');

-- Tabela Ficha Tecnica
CALL AdicionarFichaTecnica(1.85, 80.0, 'Atacante', 'João', 'Silva', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.75, 90.0, 'Defensor', 'Maria', 'Oliveira', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.82, 85.0, 'Atacante', 'Carlos', 'Santos', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.78, 75.0, 'Defensor', 'Ana', 'Costa', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.88, 78.0, 'Atacante', 'Luiz', 'Lima', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.80, 80.0, 'Defensor', 'Paula', 'Martins', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.83, 82.0, 'Atacante', 'Pedro', 'Alves', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.76, 70.0, 'Defensor', 'Fernanda', 'Ribeiro', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.90, 85.0, 'Atacante', 'Bruno', 'Gomes', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.79, 88.0, 'Defensor', 'Clara', 'Mendes', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.84, 79.0, 'Atacante', 'Miguel', 'Ferreira', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.77, 74.0, 'Defensor', 'Laura', 'Pereira', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.86, 81.0, 'Atacante', 'Thiago', 'Souza', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.78, 73.0, 'Defensor', 'Mariana', 'Oliveira', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.85, 77.0, 'Atacante', 'Gustavo', 'Rodrigues', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.76, 76.0, 'Defensor', 'Raquel', 'Fernandes', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.87, 80.0, 'Atacante', 'Felipe', 'Barbosa', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.79, 75.0, 'Defensor', 'Gabriela', 'Lopes', 'Portuguesa', @novoIdJogador);
CALL AdicionarFichaTecnica(1.88, 83.0, 'Atacante', 'Ricardo', 'Cunha', 'Brasileira', @novoIdJogador);
CALL AdicionarFichaTecnica(1.80, 72.0, 'Defensor', 'Sofia', 'Nunes', 'Portuguesa', @novoIdJogador);
